---
title: iAssistMD | Practice Management in Pooler | USA
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
phone: 888-688-3464
email: info@iassistmd.com
address: 463 Pooler Parkway, Suit 159, <br />Pooler, GA 31322
description: 'We specialize in practice management, revenue cycle optimization, and
  private practice business support

'
baseurl: ''
url: www.iassistmd.com
facebook:
  url: https://www.facebook.com/iASSISTMD/
twitter_username: jekyllrb
github_username: jekyll
sass:
  sass_dir: _sass
markdown: kramdown
permalink: pretty
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
